name: Build Project

on:
  push:
    branches:
      - main
  workflow_dispatch: # Bu tetikleyici iş akışını manuel olarak başlatmayı sağlar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Download and Set Up NDK
        run: |
          wget -q https://dl.google.com/android/repository/android-ndk-r23-linux-x86_64.zip
          unzip -q android-ndk-r23-linux-x86_64.zip
          export NDK_HOME=$PWD/android-ndk-r23

      - name: Build
        run: |
          $NDK_HOME/ndk-build -j4 -B NDK_PROJECT_PATH=. NDK_APPLICATION_MK=./Application.mk

      - name: Clean
        run: |
          $NDK_HOME/ndk-build clean NDK_PROJECT_PATH=. NDK_APPLICATION_MK=./Application.mk
